version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
  app:
    depends_on:
      - mysqldb
    image: car-sharing-app
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - ./src/main/resources/db/changelog:/db.changelog
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "$MYSQLDB_USER",
      "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
      "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
      "spring.jpa.hibernate.ddl-auto" : "validate",
      "spring.mvc.pathmatch.matching-strategy" : "$SPRING_MVC_MATCHING_STRATEGY",
      "springdoc.swagger-ui.tagsSorter" : "$SPRINGDOC_TAGS_SORTER",
      "spring.liquibase.change-log" : "$SPRING_LIQUIBASE_CHANGELOG",
      "telegram.bot.token" : "$TELEGRAM_BOT_TOKEN",
      "telegram.bot.id" : "$TELEGRAM_BOT_ID",
      "stripe.secret.key" : "$STRIPE_SECRET_KEY",
      "telegram.chat.id" : "$TELEGRAM_CHAT_ID"
      }'
